source 'https://rubygems.org'
ruby '2.7.6'

gem 'sinatra'
gem 'puma'
gem 'spotify-ruby'

group :development do
  gem 'figaro', git: 'https://github.com/bpaquet/figaro.git', branch: 'sinatra'
  gem 'byebug'
end